#!/usr/bin/bash
curl -k http://www.mingxing.com  > /dev/null
curl -k https://www.sina.com.cn > /dev/null
curl -k https://www.sohu.com > /dev/null
curl -k https://www.ifeng.com > /dev/null
curl -k https://www.qq.com > /dev/null
curl -k https://www.163.com > /dev/null
curl -k https://www.china.com > /dev/null
curl -k https://ent.sina.com.cn  > /dev/null
curl -k https://ent.163.com  > /dev/null
curl -k https://ent.qq.com  > /dev/null
curl -k https://www.mtime.com/  > /dev/null
curl -k https://www.dytt8.net/  > /dev/null
curl -k https://tv.youku.com/  > /dev/null
curl -k https://www.iqiyi.com/zongyi/  > /dev/null
curl -k https://www.67.com  > /dev/null
curl -k https://movie.youku.com  > /dev/null
curl -k https://www.m1905.com  > /dev/null
curl -k https://www.ifensi.com  > /dev/null
curl -k https://movie.douban.com  > /dev/null
curl -k https://www.hanjuwang.com  > /dev/null
curl -k https://www.cctv.com/  > /dev/null
curl -k https://www.mgtv.com  > /dev/null
curl -k https://www.dragontv.cn/  > /dev/null
curl -k https://www.gdtv.cn/  > /dev/null
curl -k http://www.xjtvs.com.cn/  > /dev/null
curl -k https://www.gdtv.cn/  > /dev/null
curl -k https://www.sctv.com/  > /dev/null
curl -k http://www.jstv.com/  > /dev/null